language: node_js

node_js:
  - 6

before_install:
  - openssl aes-256-cbc -K $encrypted_a06581e910ad_key -iv $encrypted_a06581e910ad_iv -in .npmrc.enc -out .npmrc -d

before_script:
  - npm install -g bower
  - bower install

script:
  - set -e
  - npm test
  - npm publish
  - set +e
